### ISSUE TITLE
coverage error - node-jspm-jasmine tries to import transpiled files of files where no source map exists.

### ISSUE THREAD

**Issue by internettrans** [CanopyTax/node-jspm-jasmine#11]

**Comment by internettrans** [comment]
The error I get is

```
> jspmjasmine

Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.
Started
..........................
[Error: Could not find file: "/Users/joel/workplace/end-user-forms-ui/src/source-forms/summary-table/summary-table.helpers.test.js__node-jspm-jasmine-transpiled__.js"]
[Error: Could not find source map for: "/Users/joel/workplace/end-user-forms-ui/src/source-forms/summary-table/summary-table.helpers.test.js__node-jspm-jasmine-transpiled__.js"]
```

That `summary-table.helpers.test.js` looks like this (it's just a half-written test):

```
describe('Summary Table Helpers', () => {

});
```

It seems like the error is maybe caused by the [transpiled file not being created](https://github.com/CanopyTax/node-jspm-jasmine/blob/92184674f9f19055d4af6e3f35c608235be67078/src/node-jspm-jasmine.js#L65) since [`load.metadata.sourceMap` is falsy](https://github.com/CanopyTax/node-jspm-jasmine/blob/92184674f9f19055d4af6e3f35c608235be67078/src/node-jspm-jasmine.js#L59)

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Let me know if [that pr](https://github.com/CanopyTax/node-jspm-jasmine/pull/18) fixes the issue. Instead of creating a tranpiled file without a source map, we're just providing the actual source to coverage. This should work if in fact jspm is not transpiling. If it is transpiling and there is no source map, the next thing to try is just creating the file with a mock source map. The part that I don't understand is why isn't jspm creating a sourcemap if you're using an es6 arrow function.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
@joeldenning If you figure out why jspm is not transpiling even though you're using an es6 arrow function, do lmk for curiosity sake. In my setup of jspm 0.17.0-beta.13 even a file with just "var hello = world", gets transpiled with a sourcemap included, although babel is not always involved.

**Comment by internettrans** [comment]
I think that this is fixed now with https://github.com/CanopyTax/node-jspm-jasmine/commit/6269e404fe780b7ab995be52eae6be3b97640930
