### ISSUE TITLE
Add native coverage support

### ISSUE THREAD

**Issue by blittle** [CanopyTax/node-jspm-jasmine#3]

**Comment by m-a-r-c-e-l-i-n-o** [comment]
I was going to bring this up in the next few days, it's something I'll be needing soon. Not sure if it belongs inside this project though, I wonder what @joeldenning thinks about this. My impulse is to say that it should be native because it's closely related and also to avoid having to load the jspm modules twice for the execution of two things (test and coverage) that are likely taking place at the same time. (Not sure if the latter is a very valid argument as I don't understand the system.js module loading/caching 100%, just yet.)

**Comment by blittle** [comment]
I think it would be nice if `node-jspm-jasmine` could work easily out of the box. A lot of JavaScript tooling works, but takes forever to get it to work with intermixing configuration.

**Comment by internettrans** [comment]
I agree, coverage would be something I'd love to have "just work out of o the box". I think https://github.com/jmcriffey/babel-istanbul is a good place to start investigating?? We might only be able to get coverage to work for jspm@^0.17 since we'd need babel 6, but that would be acceptable.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
I have a hunch as to what a good coverage strategy might be and I would love to further contribute to this effort, but my JSPM/SystemJS/Jasmine knowledge is fairly limited atm. 

Any chance one of you guys could give me a brief overview as to what's going on here: https://github.com/CanopyTax/node-jspm-jasmine/blob/master/src/node-jspm-jasmine.js#L96-L101 
Where are the transpiled files located/being stored?
Does a "!transpiled" and sourcemaps files always get generated?
How does Jasmine know about them? (In this script, only the spec directory is being passed to `jasmine.loadConfig()`, but I can't seem to find the transpiled files at the time of execution inside that directory. Traced the code all the way to https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine.js#L724 with no clear explanation)
Any documentation outlining the concepts being used here?

I'll write some reasonable unit tests for this project as a thank you for a thorough explanation XD

**Comment by internettrans** [comment]
@m-a-r-c-e-l-i-n-o I'll do my best to answer your questions:
1. In https://github.com/CanopyTax/node-jspm-jasmine/blob/master/src/node-jspm-jasmine.js#L96-L101, what we're doing is System.importing all of the test files. Those test files of course import the source files, etc, and also (importantly) call the global jasmine functions such as `describe`, `it`, `beforeEach`, etc. The way that jasmine works is that when you call `describe`, `it`, etc it doesn't actually run the tests, but instead waits until you call `jasmine.execute()`. So jasmine is basically just keeping track of all the functions to call once `jasmine.execute()` is called. So in our code we wait until all the tests called `describe`, `it`, etc, and before calling `jasmine.execute()`.
2. Transpiled files are only located/stored in memory inside of systemjs. SystemJS is [just eval'ing](https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L136-L143) the [transpiled code](https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L436-452). 
3. I don't have all the answers to all the questions about `!transpiled` files and sourcemaps, but here's what I _do_ know. Stacktraces that have `!transpiled` come from sourcemaps that don't really point to real files in the file system. I'm pretty sure the sourcemaps are just in memory objects that have the source file inlined into the sourcemap. So to try to answer your question, I do not believe that `!transpiled` files actually are real things at the file system level, and I also don't believe that the sourcemaps files are real files in the file system. All in memory.
4. I'm not sure I fully understand your question, but I think you're asking how Jasmine knows about the !transpiled and sourcemaps files. I think that my answer to (1) explains how all that is working -- let me know if (1) doesn't help.
5. There's definitely not any documentation for node-jspm-jasmine's implementation approach. But the concepts I used were all based on knowledge of how SystemJS and Jasmine work. https://github.com/systemjs/systemjs/blob/master/docs/system-api.md and https://github.com/systemjs/systemjs/blob/master/docs/overview.md aren't bad places to start learning about SystemJS. But overall I don't think you'll find any documentation that tells you everything, without reading SystemJS' source code.

Going back to the subject of coverage, though, what was the approach you were thinking of? What I was thinking of is to use the js api for babel-istanbul (see [home page](https://github.com/jmcriffey/babel-istanbul) and [js api](https://github.com/gotwarlost/istanbul/blob/master/README.md#instrument-code)) to instrument all of the files, [_before_ we System.import](https://github.com/CanopyTax/node-jspm-jasmine/blob/master/src/node-jspm-jasmine.js#L96) the files. Once we've got the instrumented files as an in-memory string, we would either 1) find a way to System.import the string itself, or 2) write temporary files and then System.import those temporary files. After the tests have run, we would use babel-istanbul's js api again to write out the coverage object into a `coverage` directory, preferably with HTML reports and everything. Some of those steps still have some things to iron out, but I think that we could get it working.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
> ... global jasmine functions such as describe, it, beforeEach, etc. The way that jasmine works is that when you call describe, it, etc it doesn't actually run the tests, but instead waits until you call jasmine.execute() ...

That (specifically) addresses my questions almost entirely. Thank you.

The approach I was thinking of was a very crude version of the following crude approach: 
- Import files via SystemJS
- Intercept the import with the "translate" hook
- Keep reference to source and source map (might need to save it as a physical file)
- Instrument the code with plain ol' Istanbul
- Let it proceed to the "instantiate" phase
- Generate the report 
- Remap the source using some remap library (i.e. https://github.com/SitePen/remap-istanbul) — thus my deep concern for source maps in the previous comment.

I need to do a bit more researching and experimenting to see if my approach is viable.

In your approach, would the "babel-istanbul" instrumentation still work if the user has some custom babel requirements (i.e. jsx)? From what I read, for custom rules, the user would need to supply a ".babelrc", correct? Or are you planning on automatically configuring that with the info from the jspm meta config? Or am I missing something here and it just works? Other than that, I think your approach is great.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
Worked on a proof of concept today, seems promising, here's the gist:
https://gist.github.com/m-a-r-c-e-l-i-n-o/3a36206f31d5754b00626070fa136404
@blittle @joeldenning Could really use some of your expertise right about now. Please see the comments in the code. If you guys don't think we should insist down the path I went, that's valid too :P

**Comment by internettrans** [comment]
Looks awesome -- sounds like it actually produces code coverage html reports (just with the extra directory). My one big question about it is that it seems like the coverage reports would be based on the transpiled code instead of the source code? That is definitely a huge step in the right direction, but I think we'd want to shoot for coverage results on the source code. Maybe we could add that later if that's significantly harder, but I think it would involve overwriting the System.translate hook. Let me know if I'm misunderstanding your code, though.

In regards to [your question](https://gist.github.com/m-a-r-c-e-l-i-n-o/3a36206f31d5754b00626070fa136404#file-node-jspm-jasmine-js-L189), I'm not sure I fully understand. You were asking why your commented code wasn't getting executed in the scenario where jasmine.execute() is run outside of of the promise. If you're talking about [the first jasmine.execute()](https://gist.github.com/m-a-r-c-e-l-i-n-o/3a36206f31d5754b00626070fa136404#file-node-jspm-jasmine-js-L146) then it seems that your [commented code](https://gist.github.com/m-a-r-c-e-l-i-n-o/3a36206f31d5754b00626070fa136404#file-node-jspm-jasmine-js-L189-L210) isn't being run because it's in the [`else` branch](https://gist.github.com/m-a-r-c-e-l-i-n-o/3a36206f31d5754b00626070fa136404#file-node-jspm-jasmine-js-L145-L147) and just isn't in the same code block. Am I misunderstanding your question, though? I tested out `console.log`ging right after `jasmine.execute()` and verified that the logging really did happen.

**Comment by m-a-r-c-e-l-i-n-o** [comment]
To answer your big question, the coverage reports would indeed be based on the transpiled code, however that's where source maps would come into play. Contrary to my [second to last comment ](https://github.com/CanopyTax/node-jspm-jasmine/issues/3#issuecomment-209890249) (and also somewhat addressing the questions I asked you in that comment), if I had instrumented the code at the transpile hook, I would be feeding the true source to Istanbul. But what if that source is something custom (i.e. es6/es7, jsx, coffescript, typescript)? So with that, I don't think we should try to instrument the source, and instead let jspm handle any transpiling that needs to be done according to whatever way the user configured his/her setup. Then we would do the coverage in the instantiate hook against the transpiled code and use the generated transpiled source map to map the Istanbul instrumentation back to the source! And that's where "remap-istanbul" comes in! If we were not trying to have it map back to the source, then we could have just created a [report against the transpiled code](https://gist.github.com/m-a-r-c-e-l-i-n-o/3a36206f31d5754b00626070fa136404#file-node-jspm-jasmine-js-L203-L209) and called it a day, but that would not deff not be awesome.

As for [this question](https://gist.github.com/m-a-r-c-e-l-i-n-o/3a36206f31d5754b00626070fa136404#file-node-jspm-jasmine-js-L189-L195) I'll be dammed if the issue was an else branch, hehe. But no, it's more profound. See if this example makes it clearer:

```
if (numSpecGlobsLeft === 0) {
    jasmine.execute();
} else {
    specFiles.forEach(globPattern => {
        glob(specDir + '/' + globPattern, {}, function(err, files) {
            if (err) {
                throw err;
            }

            Promise
            .all(files.map(file => SystemJS.import(file)))
            .then(() => {
                if (--numSpecGlobsLeft === 0) {
                    jasmine.execute();

                    console.log("Does this log for you? It doesn't for me.")
                    throw new Error("Is this thrown for you? It doesn't for me.")

                    // My guess is that maybe reports are generated inside try 
                    // and catch in Jasmine and therefore execution is stopped
                    // when the reports are made? But AFAIK the tests run
                    // asynchronously, so that wouldn't apply. Anyway I figured 
                    // out a way around it, but not understanding this behavior  
                    // is slowly killing me... 
                }
            })
            .catch(errCallback);
        });
    });
}
```

**Comment by internettrans** [comment]
#7 fixes this
